-- Oracle schema for TaskFlow
-- Executed automatically by Spring Boot when spring.jpa.hibernate.ddl-auto is set to validate or none
-- For fresh setup, use ddl-auto=create or run these scripts manually

CREATE TABLE CATEGORIA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE TAREFA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(200) NOT NULL,
    descricao VARCHAR2(1000),
    categoria_id NUMBER NOT NULL,
    prazo DATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDENTE' NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_conclusao TIMESTAMP,
    CONSTRAINT fk_tarefa_categoria FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(id)
);

-- Seed categories
INSERT INTO CATEGORIA (nome) VALUES ('TRABALHO');
INSERT INTO CATEGORIA (nome) VALUES ('ESTUDOS');
INSERT INTO CATEGORIA (nome) VALUES ('PESSOAL');
INSERT INTO CATEGORIA (nome) VALUES ('URGENTE');

CREATE INDEX idx_tarefa_status ON TAREFA(status);
CREATE INDEX idx_tarefa_categoria ON TAREFA(categoria_id);
CREATE INDEX idx_tarefa_prazo ON TAREFA(prazo);
